/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AcknowledgeEvent, } from "./components/alert-lisa/alert-lisa";
export namespace Components {
    interface AlertLisa {
        "kind": "info" | "succes" | "error";
        "text": string;
    }
    interface SearchLeonie {
    }
    interface TextimgLeonie {
    }
}
declare global {
    interface HTMLAlertLisaElement extends Components.AlertLisa, HTMLStencilElement {
    }
    var HTMLAlertLisaElement: {
        prototype: HTMLAlertLisaElement;
        new (): HTMLAlertLisaElement;
    };
    interface HTMLSearchLeonieElement extends Components.SearchLeonie, HTMLStencilElement {
    }
    var HTMLSearchLeonieElement: {
        prototype: HTMLSearchLeonieElement;
        new (): HTMLSearchLeonieElement;
    };
    interface HTMLTextimgLeonieElement extends Components.TextimgLeonie, HTMLStencilElement {
    }
    var HTMLTextimgLeonieElement: {
        prototype: HTMLTextimgLeonieElement;
        new (): HTMLTextimgLeonieElement;
    };
    interface HTMLElementTagNameMap {
        "alert-lisa": HTMLAlertLisaElement;
        "search-leonie": HTMLSearchLeonieElement;
        "textimg-leonie": HTMLTextimgLeonieElement;
    }
}
declare namespace LocalJSX {
    interface AlertLisa {
        "kind"?: "info" | "succes" | "error";
        "onAcknowlegde"?: (event: CustomEvent<AcknowledgeEvent>) => void;
        "text"?: string;
    }
    interface SearchLeonie {
        "onEvClick"?: (event: CustomEvent<any>) => void;
        "onEvClose"?: (event: CustomEvent<any>) => void;
        "onEvSearch"?: (event: CustomEvent<any>) => void;
    }
    interface TextimgLeonie {
        "onEvHover"?: (event: CustomEvent<any>) => void;
        "onEvText"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "alert-lisa": AlertLisa;
        "search-leonie": SearchLeonie;
        "textimg-leonie": TextimgLeonie;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "alert-lisa": LocalJSX.AlertLisa & JSXBase.HTMLAttributes<HTMLAlertLisaElement>;
            "search-leonie": LocalJSX.SearchLeonie & JSXBase.HTMLAttributes<HTMLSearchLeonieElement>;
            "textimg-leonie": LocalJSX.TextimgLeonie & JSXBase.HTMLAttributes<HTMLTextimgLeonieElement>;
        }
    }
}
